AWSTemplateFormatVersion: "2010-09-09"
Resources:
  LambdaRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument: #the trust policy that is associated with this role
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Path: /
      Policies: #adds a access policy to the role
        - PolicyName: root
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: "*"
                Resource: "*"
  RootInstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Path: /
      Roles:
        - !Ref LambdaRole #refer to the role
    
  MyLambdaFunction: #need deployment package (zip file) & execution role
    Type: AWS::Lambda::Function
    Properties:
      Role: !GetAtt LambdaRole.Arn
      Runtime: "nodejs18.x"
      Handler: index.handler  #the name of the method within the code that lambda calls
      Code:
        ZipFile: |
          exports.handler = async (event) => {
              console.log(JSON.stringify(event));
              const response = {
                  statusCode: 200,
                  body: JSON.stringify('Hello from Lambda!'),
              };
              return response;
          };

#aws cloudformation create-stack --stack-name lambda103 --template-body file://lambda101.yaml --capabilities CAPABILITY_NAMED_IAM
