AWSTemplateFormatVersion: "2010-09-09"

Description: Create IAM Users.

# 1. IAM Uer Group
# 2. IAM Users
# 3. Policies - Attach Policies to the group
# Problems
# 1. Generate Password Programmatically - CloudFormation Custom Resources
# 2. Reduce redundant or repetitive code

Resources:
  RandomStringCustomResource:
    Type: "Custom::RandomString"
    Properties:
      length: 25
      ServiceToken: !ImportValue RandomizerLambdaArnB2301 # Importing value exported by another cloudformation template
  RandomStringCustomResource2:
    Type: "Custom::RandomString"
    Properties:
      length: 25
      ServiceToken: !ImportValue RandomizerLambdaArnB2301

  RandomStringCustomResource3:
    Type: "Custom::RandomString"
    Properties:
      length: 25
      ServiceToken: !ImportValue RandomizerLambdaArnB2301

  StudentsReadOnlyGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: StudentsReadOnlyGroup
  #      Policies:
  #        - Policy

  StudentsReadOnlyPolicy:
    Type: AWS::IAM::Policy
    Properties:
      Groups:
        - !Ref StudentsReadOnlyGroup
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: "*"
            Resource: "*"
      PolicyName: StudentsReadOnlyPolicy

  StudentJohn:
    Type: AWS::IAM::User
    Properties:
      Groups:
        - !Ref StudentsReadOnlyGroup
      LoginProfile:
        Password: !GetAtt RandomStringCustomResource.RandomString
        PasswordResetRequired: true
      UserName: StudentJohn

  StudentDohn:
    Type: AWS::IAM::User
    Properties:
      Groups:
        - !Ref StudentsReadOnlyGroup
      LoginProfile:
        Password: !GetAtt RandomStringCustomResource2.RandomString
        PasswordResetRequired: true
      UserName: StudentDohn

  StudentMon:
    Type: AWS::IAM::User
    Properties:
      Groups:
        - !Ref StudentsReadOnlyGroup
      LoginProfile:
        Password: !GetAtt RandomStringCustomResource3.RandomString
        PasswordResetRequired: true
      UserName: StudentMon

Outputs:
  RandomString:
    Description: RandomString Value
    Value: !GetAtt RandomStringCustomResource.RandomString
  RandomString2:
    Value: !GetAtt RandomStringCustomResource2.RandomString
  RandomString3:
    Value: !GetAtt RandomStringCustomResource3.RandomString
# aws cloudformation create-stack --stack-name b2301-manage-iam-users --template-body file://manage-iam-users.yaml.yaml
# aws cloudformation create-stack --stack-name b2301-manage-iam-users --template-body file://manage-iam-users.yaml --capabilities CAPABILITY_NAMED_IAM

# aws cloudformation create-change-set --stack-name b2301-manage-iam-users --change-set-name first-change-set --change-set-type CREATE --template-body file://manage-iam-users.yaml.yaml

# aws cloudformation validate-template --template-body file://manage-iam-users.yaml

